# Generated by Django 5.1.6 on 2025-02-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_customuser_teaching_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('dydaktyk', 'Dydaktyk'), ('administrator', 'Administrator')], default='student', max_length=15, null=True),
        ),
    ]
