# Generated by Django 4.2.19 on 2025-02-08 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='semester_group',
            field=models.CharField(blank=True, help_text='Dwucyfrowy kod grupy (np. 10, 21)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='final_value',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('zal', 'zal')], help_text='Wartość wyliczana na podstawie ocen cząstkowych', max_length=10),
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='row_color',
            field=models.CharField(blank=True, default='', help_text='Kolor wiersza w formacie hex (np. #ffffff)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='partialgrade',
            name='attempt1',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('zal', 'zal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='partialgrade',
            name='attempt2',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('zal', 'zal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='partialgrade',
            name='attempt3',
            field=models.CharField(blank=True, choices=[('', '-----'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('zal', 'zal')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='partialgrade',
            unique_together={('final_grade', 'form')},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], help_text='Dzień tygodnia')),
                ('start_time', models.TimeField(help_text='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(help_text='Godzina zakończenia')),
                ('lesson_type', models.CharField(choices=[('wykład', 'Wykład'), ('laboratoria', 'Laboratoria'), ('audytoria', 'Audytoria'), ('kolokwium', 'Kolokwium'), ('kolokwium poprawkowe', 'Kolokwium poprawkowe'), ('zaliczenie', 'Zaliczenie'), ('zaliczenie poprawkowe', 'Zaliczenie poprawkowe')], help_text='Forma zajęć', max_length=30)),
                ('mandatory', models.BooleanField(default=True, help_text='Czy zajęcia są obowiązkowe')),
                ('additional_info', models.TextField(blank=True, help_text='Dodatkowe informacje')),
                ('group', models.CharField(blank=True, help_text='Grupa, dwucyfrowy kod', max_length=2)),
                ('final_grade', models.ForeignKey(help_text='Przedmiot (ocena) dla zajęć', on_delete=django.db.models.deletion.CASCADE, to='core.finalgrade')),
            ],
        ),
    ]
