# Generated by Django 4.2.19 on 2025-02-08 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_lesson_day_of_week_lesson_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.CharField(default=200, help_text='Sala (3-cyfrowa)', max_length=3, validators=[django.core.validators.RegexValidator(message='Podaj 3-cyfrową salę', regex='^\\d{3}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('wyklad', 'Wykład'), ('laboratoria', 'Laboratoria'), ('audytoria', 'Audytoria'), ('kolokwium', 'Kolokwium'), ('kolokwium poprawkowe', 'Kolokwium poprawkowe'), ('zaliczenie', 'Zaliczenie'), ('zaliczenie poprawkowe', 'Zaliczenie poprawkowe'), ('odwolane', 'Odwołane')], help_text='Forma zajęć', max_length=30),
        ),
    ]
