# Generated by Django 5.1.6 on 2025-02-22 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('ects', models.FloatField(help_text='Podaj ECTS przedmiotu przy tworzeniu pierwszej oceny cząstkowej')),
                ('final_value', models.CharField(blank=True, choices=[('', '-----'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('zal', 'zal')], help_text='Wartość wyliczana na podstawie ocen cząstkowych', max_length=10)),
                ('row_color', models.CharField(blank=True, default='', help_text='Kolor wiersza w formacie hex (np. #ffffff)', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartialGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('audytoria', 'Audytoria'), ('laboratoria', 'Laboratoria'), ('wyklad', 'Wykład')], max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='Waga oceny cząstkowej')),
                ('attempt1', models.CharField(blank=True, choices=[('', '-----'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('zal', 'zal')], max_length=10)),
                ('attempt2', models.CharField(blank=True, choices=[('', '-----'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('zal', 'zal')], max_length=10)),
                ('attempt3', models.CharField(blank=True, choices=[('', '-----'), ('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('zal', 'zal')], max_length=10)),
                ('final_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.finalgrade')),
            ],
            options={
                'unique_together': {('final_grade', 'form')},
            },
        ),
    ]
