# Generated by Django 5.1.6 on 2025-02-22 19:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data zajęć')),
                ('start_time', models.TimeField(help_text='Godzina rozpoczęcia')),
                ('end_time', models.TimeField(help_text='Godzina zakończenia')),
                ('lesson_type', models.CharField(choices=[('wyklad', 'Wykład'), ('laboratoria', 'Laboratoria'), ('audytoria', 'Audytoria'), ('kolokwium', 'Kolokwium'), ('kolokwium poprawkowe', 'Kolokwium poprawkowe'), ('zaliczenie', 'Zaliczenie'), ('zaliczenie poprawkowe', 'Zaliczenie poprawkowe'), ('odwolane', 'Odwołane')], help_text='Forma zajęć', max_length=30)),
                ('mandatory', models.BooleanField(default=True, help_text='Czy zajęcia są obowiązkowe')),
                ('additional_info', models.TextField(blank=True, help_text='Dodatkowe informacje')),
                ('group', models.CharField(help_text='Grupa, dwucyfrowy kod', max_length=2)),
                ('room', models.CharField(help_text='Sala (3-cyfrowa)', max_length=3, validators=[django.core.validators.RegexValidator(message='Podaj 3-cyfrową salę', regex='^\\d{3}$')])),
                ('final_grade', models.ForeignKey(help_text='Przedmiot (ocena) dla zajęć', on_delete=django.db.models.deletion.CASCADE, to='grades.finalgrade')),
            ],
        ),
    ]
